### ISSUE TITLE
Drop Git (and Markdown) from instructor training?

### ISSUE THREAD

**Issue by wking** [swcarpentry/training-course#453]
On Mon, Apr 06, 2015 at 10:53:56AM -0700, Bill Mills [wrote](https://github.com/swcarpentry/training-course/issues/445#issuecomment-90174433):

> I'm beginning to think that git proficiency is overemphasized in
> Instructor Training. … It might make sense to take git usage out of
> Instructor Training entirely, and offer training seminars to those
> people who would like them, if and when they'd like to contribute
> back to the lessons…

With Git training already in swcarpentry/git-novice,
BillMills/git-help-session, and innumerable other places, this sounds
workable to me.  We'd have to drop the GitHub-hosted-blog as a
submission format though.  Is the alternative submission procedure
just “email your instructor”?

And [again](https://github.com/swcarpentry/training-course/issues/445#issuecomment-88658069), I think it would also be reasonable to require
trainees to aquire something like novice-workshop skills before 
starting training.  Deciding where the balance lies depends on:
- How easy it is for prospective trainees to attend a novice workshop
  or evaluate their externally-gained skills against that bar?
- How much of a imposter-syndrome barrier would the prerequisite
  create?
- How much instructor-training capacity do we have?

If we have lots of capacity, I'm fine putting anyone who wants to come
through the course, and let them sort out their Git training (or skip it)
whenever they want.  If we have limited capacity, then restricting
enrolment to Git-capable trainees would help weed out the unmotivated
(but it would also weed out imposter-syndrome folks and otherwise
good instructors who just have a Git block).  Still, no filter is perfectly
sensitive and specific, so if we need a filter, it's a judgment call whether
the Git-capable filter's benefits (we know trainees will be able to
contribute to lesson development) outweight its costs (we miss
out on some potentially good trainees).

**Comment by mtb-za** [comment]
Yeah, the only(?) reason that git is getting so much attention is because it is being used as the backend for the blog. If it was not needed, then it would be more background knowledge, like Python/R/MATLAB/shell is. This is the first time that it has been used, as opposed to something like WordPress. So, is there a way to make submitting to a Jekyll blog as easy as posting on WordPress?

Maybe something like https://github.com/swcarpentry/training-course/pull/451#issuecomment-89384502 might be enough, which is a couple of screenshots (in a larger discussion) of just using GitHub's web-interface to create a new page in the Round 12 instructors' blog (although I did not pull the trigger on creating the page).

Note that it will create a fork in the background if you do not have one. So there would still be overhead in order to ensure that one's own fork is up to date regarding the new one. I need to play with this a little, and could then write a basic guide to doing this, if people think this could address things.
