### ISSUE TITLE
Format and registration fee for instructor training

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/training-course#514]
We ran an instructor training course online for the NIH last week over 1.5 days, and it went very well.  The learners were in two rooms (20 in one room, 3 in another at a remote site); Greg taught via tele-conferencing with a mixture of webcam and screen sharing, and the curriculum was pretty much the same as always.  As a result, we're wondering if we should run it that way more often, and would like to know:
1.  **Would you have preferred to set aside two full days to go through training rather than spreading it out over several weeks?** (Assume for the sake of discussion that we can avoid the problems with Git and GitHub that we've experienced in this round, either by changing platforms or by offering an online short course or some extended mentoring.)
2.  **Would you have been willing to pay $40 to register for such a course?**  (This is what we recommend charging workshop participants in order to cut the no-show rate.)

Please add your thoughts to this issue.

**Comment by IanHawke** [comment]
I attended the TGAC course which did in person back in October and [blogged about it here](http://ngcm.soton.ac.uk/blog/2014-10-24/software-carpentry-instructor-training-workshop-tgac.html). I thought it was excellent.
- It was easier to fit an intensive, 2 day, course around my other commitments than spreading it over several weeks.
- It was more effective than previous teacher training courses I've done. I believe this was partially the intensive nature.
- I would have been willing to pay of the order of £50 to register (travel and accommodation costs make that fee negligible, but even teleconferencing it I'd still have paid).

Caveats: I'm in a position where I could expense-claim those costs, so time is far more important than cash.

**Comment by embaldridge** [comment]
I would personally prefer a two day intensive course.  I understand the desire to prevent no-shows, and I can afford the $40.  However, that being said, it seems odd to ask folks to pay to take a course so they can learn how to volunteer-teach for an organization.

**Comment by ericmjl** [comment]
Agreed with @embaldridge about the course fee. The alternative is to make it a refundable deposit contingent on attendance - if you attend, you get the $40 back; no-shows effectively donate the money to SW. Just throwing an idea out there.

+1 also for 2-day intensive course.

**Comment by laurajanegraham** [comment]
I quite liked the spread out format, I felt that it allowed me time to think about postings/tasks before doing them, which helped me to get a bit more out of it. If I were to do a 2 day intensive course though, I think I would be happy to pay the fee because we are learning new skills from the training.

**Comment by kaizhuang** [comment]
I would much much prefer the 2 day intensive course. I have been meaning to do the instructor course for 2 years now, but could never find consistent free time over many weeks to do it with work and family responsibilities.

I have no problem shelling out $40 personally, although I suspect I can get it covered by my university.

**Comment by iamc** [comment]
Being in the next instructor's slot, I'd also prefer the two days intensive option.

No problem also with paying such amount for registering. @ericmjl idea sounds good, but would likely involve a lot of bureaucracy for the organizers.

**Comment by billyc** [comment]
I'm also signed up for the next instructor training. 2 days intensive would be far easier for me to schedule; but I have a hunch I'd retain more knowledge if it was spread out. 

I think I'd pay $40 for this training (even if out of pocket) if it was made clear what that money was going toward.

**Comment by poliquin** [comment]
:+1: for the 2-day intensive session. I am willing to pay $40, but also like the proposal to refund the deposit for people who show up.

**Comment by PBarmby** [comment]
An intensive 2-day course would likely have required 3+ days away from home for me, which would have been tough to arrange. Spread-out online worked better for me.

**Comment by embaldridge** [comment]
Along with @PBarmby, if travel is required for instructor training, that's problematic.  I like the idea of the two day intensive, but the remote access part is essential for me, so if the remote part isn't as feasible with a two day intensive, then spread out is definitely preferable.

**Comment by tmogrady** [comment]
I'm signed up for the next instructor training too, and like @billyc I think the two-day (remote-access) idea sounds great for scheduling but that things might stick a little better if I'm forced to think about them over several weeks. I don't have strong feelings either way.

As for the $40, yes I'd be willing to pay, partly because I think I can get it covered by my fellowship. But remember that for those of us who are grad students living on stipends, $40 could be kind of a lot.

**Comment by richford** [comment]
I agree with @billyc that the longer format increases retention. I'm glad that I had enough time to think more critically about the material. I was able to digest it slowly and think about how it applies to my own academic history. It made me a better teacher as promised but I think it also made me a more sympathetic learner...more forgiving of my teachers' shortcomings. I'm skeptical that a 2-day intensive course would've given me the same.

On a purely practical note, how do the 2-day intensive workshop attendees read How Learning Works?

I would've been willing to pay $40 for the instructor training and I like @ericmjl's idea about refunding attendees.

**Comment by ivastar** [comment]
Were you able to cover the same amount of material in an intensive 2-day workshop as the multi-week one? I'd also be worried about being able to get enough practice and remember a significant portion of the material if a lot of information is crammed into a short time. In any case, I'd be happy to participate in either format. 

I'd be happy to pay $40 for the instructor training. Where does the $40 go? I can imagine an in-person workshop requires some expenses for the space and coffee (there's coffee, right?). However, I'd also take advantage of the remote option, because I don't have travel funds available that I can use for this purpose. Travel to a nearby large city + hotel for 2 nights will be > $500 in out of pocket expenses.

**Comment by SaraVarela** [comment]
Hi everybody, 

I'd rather prefer 2 intensive days and I think that 40$ is a reasonable fee for the course. 

best regards, 
Sara

**Comment by johnsolk** [comment]
I like the idea of an intensive 2-day online training (get 'er done!) but think that the concepts might stick around more and be solidified if discussed and practiced over a longer time period since learning platform is online and not in-person.

As for the fee, agree with @tmogrady about $40 being a lot for grad students. It is important to me, so willing to pay and agree with incentive for accountability, but like the refund option.

**Comment by rgaiacs** [comment]
> Would you have preferred to set aside two full days to go through training rather than spreading it out over several weeks?

One thing that I like about spreading it out over several weeks is that it allow the students to read the reference that we use.

Since the intensive 2 days format will, probably, reduce the drop out rate I'm +1/2 for this.

**Comment by snim2** [comment]
1. I'm not sure whether I would have been able to take 2 days off; depends on timing.
2. Probably, if travel costs were not excessive

**Comment by mjcollin** [comment]
I greatly preferred the online course. Having concepts presented serially with time to reflect on them and have events occur in my "real" life that were opportunities to apply those concepts made them much more concrete. A 2-day intensive is great for engagement and focus but I'm susceptible to cramming and dumping knowledge.

If it's a 2-day course with travel, $40 is nothing comparatively speaking. If it's online, perhaps waiving the fee for enrolled students would soften it? I think nothing of paying $40 for professional development but I have the luxury of a livable salary.

**Comment by anjakefala** [comment]
Hi! I've one of the "drop-outs" of the multi-week course design. I dropped out for the last submission. And my issue was that the last submission part of the course took place during the final examination period. I had a lot of exams and papers. The problem with the multi-week design being, of course, that some weeks are higher pressure than others.

However, I really enjoyed having the time to read the text and think about the assignments over the course of the multi-week but when it stretched into high pressure zones, it became harder to consistently commit. 

I will definitely apply for the 2 day intense course because I think it's a nice way to supplement and complete my learning. I think the 40$ is reasonable.

The ideal balance may be a bit of both. Having the bulk of it occur over the 2 days but then have some remote meetups occurring after between the students which you use to fine tune and integrate what you learned over the 2 days before teaching your first course. I liked the process of being paired with someone and having my teaching techniques being critiqued by them.

**Comment by kbroman** [comment]
I prefer the spread-out version; I think I learned more that way.

The $40 seems reasonable, but I agree with @embaldridge, that it's a bit awkward in the context of required preparation for volunteering to teach.

**Comment by ttimbers** [comment]
I would have liked to do a 2 day workshop instead of having it spread over weeks, especially if it meant working in a smaller group and getting to know other instructors going through the training. Although we gave each other feedback in the multi-week online instructor training, I didn't interact with the same person more than once and I didn't really get to know anyone else in my cohort. 

One concern I have, is how we will logistically deal with this with people in remote areas, or areas where there are no others going through instructor training. I am sure we can think of solutions, but it might not always be as simple as conferencing the trainer of the trainers (i.e. Greg or whomever else is running the instructor training) into a room full of instructors to be.

I probably would have paid $40 to register for such a course.

**Comment by burkesquires** [comment]
Having taken the two-day intensive version (here at the NIH) and experiencing some of the extended version, I think the two-day version was great and my preference. It worked incredibly well.

The registration fee fo $40 is not onerous as far as cost goes but as we discussed it can be difficult to allocate even $1 depending upon the setup of the course.

**Comment by iamc** [comment]
I totally agree with @damedebugger about a 2 days intensive course for the bulk of the thing and a bit of a slower pace work afterwards. In fact I did assume something on these lines, as I did not think that after a two days course you'd automatically get the "instructors" grade, did you?

**Comment by anjakefala** [comment]
It might be! I'm not sure about the structure of the 2-day course. I only participated in the multi-week one.

**Comment by timtroendle** [comment]
While I see the benefits to retention in a spread-out training, I'd prefer a 2 days course for its intensity and the full attention one could pay to it.

The 40$ registration fee probably wouldn't keep me from attending the training but I agree with @embaldridge and I'm wondering whether it's the right instrument to keep people from not showing up. I'd like to know how this money is used in such a case; as far as I understood these trainings are fully covered by the administrative fee for workshops so far.

**Comment by narayananr** [comment]
I like the long format and $40 fee would not deter me from attending the training program. I felt the long format allowed me to put some thing I learned in to practice. For example, the long format made me a newbie github user to a regular github user.

**Comment by emhart** [comment]
I think the long format has its advantages and disadvantages. I liked having time to complete 'assignments' like filming myself teaching.  However I think I would be able to be more focused if it was just over 2 days.  I think that no matter what you'll cut off a certain demographic if you use just one format.  Is that a reason you can't do both? I know that now I could never get 2 days, but as a graduate student it would have been much easier.  

The fee I think would be fine, especially if I paid it and was refunded on attendance (as has been already suggested).  I also agree with @embaldridge that it's a bit tough to swallow the fact that SWC is charging on both ends (students and instructors).    The refund helps deter drop-outs and makes people feel good about paying the fee.

**Comment by ostephens** [comment]
The long format worked better for me both in terms of time and expense. I would have struggled to find the time to attend a two day workshop, and the cost of travel and overnight accommodation would have added further barriers.

I'd like to both think and say that a $40 fee wouldn't have put me off, but I'm not 100% certain this is true. I guess it would have made me think (as is the intention) what my commitment to the course was and made me think again about signing up. I think there is a small possibility this would have resulted in me not signing up.

**Comment by JCSzamosi** [comment]
I would prefer the longer format, both in terms of scheduling and learning. WRT pedagogy, I think I would get much more out of a course that's spread out and gives me time to reflect between lessons. WRT scheduling, I generally find it quite difficult to clear a whole weekend (or other two-day stretch) for a single activity. If travel were required, that would more or less kill the option of me doing the course.

ETA: I would be willing to pay the $40 either as a payment or a no-show deposit. I think making it a no-show deposit would be more equitable for people who might not be able to afford the workshop.

**Comment by cmmcquaw** [comment]
I would prefer to set aside two full days for training instead of spreading it out.  It is easier for me to request two full days from work (if necessary) than it is to guarantee numerous evenings.

I would be willing to pay $40 to register for two days of intensive training.  I would be willing to pay up to $100 if (a) the use of funds was clearly identified (e.g. location fees, donation to swcarpentry) and (b) a portion was refunded at completion of course.

**Comment by aurielfournier** [comment]
I probably would have gotten more out of a two day course, but being able to do so, or get to somewhere to attend such a course, would have been very difficult, and I probably wouldn't have done it if i had to travel somewhere. 

If it was during the week during the school year there is no way I could convince all the people I am responsible to that I can step away for two whole days for this training (they are supportive of me going to teach, though they are mystified why i want to do it for free, I can't convince them what they pay me to teach now is basically for free). So if that had been the format my becoming part of SWC would have had to wait another year until I am done with taking classes and only had my teaching schedule to juggle (well that and research). 

If I was already having to travel somewhere for two days, another $40 on top of it isn't going to be a very welcome thing, I pay for all this kind of stuff out of my own pocket and as a phd student supporting a family that money isn't abundant. If it was online, I could manage $40, but it would have made me stop and think about singing up after it was suggested I do instructor training.

**Comment by huguesfontenelle** [comment]
I prefer **spreading out** (aka long format):
- Taking two days off from work would actually make the course much more expensive that $40
- Having three time slots was quite flexible. In one case I followed the lesson at 1 am (I'm in Europe), which was still a good alternative to skipping it (something else got in the way).
- pedagogy was a really new topic for me, so I'm glad I had two weeks in between lessons to digest it, read a chapter of the book, and do the assignments. If the topic was more familiar I would have preferred intensive (like programming in a new language)

I'm not sure that I would have volunteered $40 in order to volunteer as in instructor.

**Comment by iglpdc** [comment]
I think the ideal would be to have the two formats. Some people (mostly from academia) can afford/ask two days off work to attend the course, while people with other commitments cannot. I'd keep the two-day training as the default, but still offer the online extended version for folks that cannot make it.

As for the $40, I think is fair (in fact, cheap) for the training you're getting. We could waived for people that cannot afford it, but in general I see no problem in charging a small fee.

**Comment by prtkm** [comment]
I think the 2-day training would be more suitable for people already familiar with the tools, i.e. git, unix, python. But a spread out version would suit beginners better, I would think. I would personally like the 2-day version. I'm signed up for the next iteration of the instructor training and had a couple of questions about the two day training.

How would the scheduling work so that everyone is together at the same time? Would the participants be required to travel or is it remote access? Is it going to be a live teleconference or recorded material?

I don't have problems with the 40$ fee.

**Comment by lwjohnst86** [comment]
1. **Length of training**: I'm conflicted here. I like the idea of just chunking time away for an intensive 2-day workshop on training how to teach for efficiency, but I am also the type of person that needs some time to process all the information and to think it over. What about a sort of _hybrid_ option that has an intensive nature to it, but in order to complete the training you need to finish one or more assignments over the next couple of weeks post workshop? Once completed, you get the badge or certification or whatnot showing you completed the training? This would be a compromise between both methods, a shorter timeframe compared to the current method, but allows some 'cognitive fermentation' post-2-day-workshop to allow the content to be digested and applied.
2. **Fee**: I agree with @embaldridge regarding paying for getting training to then volunteer teach.  However, I do like @ericmjl suggestion about getting a refund back if you attend and otherwise don't for those no-shows.

**Comment by sshende** [comment]
The extended format is more appealing for me just because it allows for more time to think through the subtext within the lessons, and to interact more meaningfully with the instructors and fellow learners taking the course. That said, I am already quite familiar with many of the topics so a two-day course would work just fine for me. 

I am perfectly ok with the $40 fee for the course, provided it come with significant expenses for travel/accommodations if the course is hosted far from where I live.

**Comment by jni** [comment]
Man that was a long thread. Is anyone compiling these? =)

My votes:
1. **spread-out**/intensive 2-day: I vote spread-out, with a suggestion towards a mix. I _really_ enjoyed having time to read the materials and then discuss in a 1h lecture/discussion. But I know people who did an intensive course here in Melbourne and they loved that also, so if I had my time over I'd like to do the spread out course _and then_ attend a 1-day intensive refresher. (Also, I think spreading the final stage, PRs + teaching demo, over such a long time is a mistake. It definitely killed the momentum for me.)
2. payment: not a big deal for me, but I second @ericmjl 's suggestion: a **deposit** seems to be the fairest solution. As others have commented, it does feel a bit rich to pay so you can volunteer.

**Comment by lwjohnst86** [comment]
After reading @jni's comment regarding the final stage, I completely agree there. I've been doing the final stage, but I definitely feel the momentum has dropped for me.
